/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../lib/axios-instance";
import type { RequestConfig, ResponseErrorConfig } from "../../lib/axios-instance";
import type { ChatStreamMutationRequest, ChatStreamMutationResponse, ChatStream422 } from "../types/ChatStream.ts";

function getChatStreamUrl() {
  const res = { method: 'POST', url: `/chat/` as const }  
  return res
}

/**
 * @summary Chat Stream
 * {@link /chat/}
 */
export async function chatStream(data: ChatStreamMutationRequest, config: Partial<RequestConfig<ChatStreamMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<ChatStreamMutationResponse, ResponseErrorConfig<ChatStream422>, ChatStreamMutationRequest>({ method : "POST", url : getChatStreamUrl().url.toString(), data : requestData, ... requestConfig })  
  return res.data
}