/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../lib/axios-instance";
import type { RequestConfig, ResponseErrorConfig } from "../../lib/axios-instance";
import type { CreateMessageMutationRequest, CreateMessageMutationResponse, CreateMessagePathParams, CreateMessage422 } from "../types/CreateMessage.ts";

function getCreateMessageUrl(conversation_id: CreateMessagePathParams["conversation_id"]) {
  const res = { method: 'POST', url: `/conversations/${conversation_id}/messages/` as const }  
  return res
}

/**
 * @summary Create Message
 * {@link /conversations/:conversation_id/messages/}
 */
export async function createMessage(conversation_id: CreateMessagePathParams["conversation_id"], data: CreateMessageMutationRequest, config: Partial<RequestConfig<CreateMessageMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<CreateMessageMutationResponse, ResponseErrorConfig<CreateMessage422>, CreateMessageMutationRequest>({ method : "POST", url : getCreateMessageUrl(conversation_id).url.toString(), data : requestData, ... requestConfig })  
  return res.data
}