/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../lib/axios-instance";
import type { RequestConfig, ResponseErrorConfig } from "../../lib/axios-instance";
import type { CreateConversationMutationRequest, CreateConversationMutationResponse, CreateConversation422 } from "../types/CreateConversation.ts";

function getCreateConversationUrl() {
  const res = { method: 'POST', url: `/conversations/` as const }  
  return res
}

/**
 * @summary Create Conversation
 * {@link /conversations/}
 */
export async function createConversation(data?: CreateConversationMutationRequest, config: Partial<RequestConfig<CreateConversationMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<CreateConversationMutationResponse, ResponseErrorConfig<CreateConversation422>, CreateConversationMutationRequest>({ method : "POST", url : getCreateConversationUrl().url.toString(), data : requestData, ... requestConfig })  
  return res.data
}