/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../lib/axios-instance";
import type { RequestConfig, ResponseErrorConfig } from "../../lib/axios-instance";
import type { DeleteConversationMutationResponse, DeleteConversationPathParams, DeleteConversation422 } from "../types/DeleteConversation.ts";

function getDeleteConversationUrl(conversation_id: DeleteConversationPathParams["conversation_id"]) {
  const res = { method: 'DELETE', url: `/conversations/${conversation_id}` as const }  
  return res
}

/**
 * @summary Delete Conversation
 * {@link /conversations/:conversation_id}
 */
export async function deleteConversation(conversation_id: DeleteConversationPathParams["conversation_id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<DeleteConversationMutationResponse, ResponseErrorConfig<DeleteConversation422>, unknown>({ method : "DELETE", url : getDeleteConversationUrl(conversation_id).url.toString(), ... requestConfig })  
  return res.data
}