/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../lib/axios-instance";
import type { RequestConfig, ResponseErrorConfig } from "../../lib/axios-instance";
import type { DeleteMessageMutationResponse, DeleteMessagePathParams, DeleteMessage422 } from "../types/DeleteMessage.ts";

function getDeleteMessageUrl(conversation_id: DeleteMessagePathParams["conversation_id"], message_id: DeleteMessagePathParams["message_id"]) {
  const res = { method: 'DELETE', url: `/conversations/${conversation_id}/messages/${message_id}` as const }  
  return res
}

/**
 * @summary Delete Message
 * {@link /conversations/:conversation_id/messages/:message_id}
 */
export async function deleteMessage(conversation_id: DeleteMessagePathParams["conversation_id"], message_id: DeleteMessagePathParams["message_id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<DeleteMessageMutationResponse, ResponseErrorConfig<DeleteMessage422>, unknown>({ method : "DELETE", url : getDeleteMessageUrl(conversation_id, message_id).url.toString(), ... requestConfig })  
  return res.data
}