/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../lib/axios-instance";
import type { RequestConfig, ResponseErrorConfig } from "../../lib/axios-instance";
import type { GetConversationQueryResponse, GetConversationPathParams, GetConversation422 } from "../types/GetConversation.ts";

function getGetConversationUrl(conversation_id: GetConversationPathParams["conversation_id"]) {
  const res = { method: 'GET', url: `/conversations/${conversation_id}` as const }  
  return res
}

/**
 * @summary Get Conversation
 * {@link /conversations/:conversation_id}
 */
export async function getConversation(conversation_id: GetConversationPathParams["conversation_id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetConversationQueryResponse, ResponseErrorConfig<GetConversation422>, unknown>({ method : "GET", url : getGetConversationUrl(conversation_id).url.toString(), ... requestConfig })  
  return res.data
}