/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../lib/axios-instance";
import type { RequestConfig, ResponseErrorConfig } from "../../lib/axios-instance";
import type { GetMessageQueryResponse, GetMessagePathParams, GetMessage422 } from "../types/GetMessage.ts";

function getGetMessageUrl(conversation_id: GetMessagePathParams["conversation_id"], message_id: GetMessagePathParams["message_id"]) {
  const res = { method: 'GET', url: `/conversations/${conversation_id}/messages/${message_id}` as const }  
  return res
}

/**
 * @summary Get Message
 * {@link /conversations/:conversation_id/messages/:message_id}
 */
export async function getMessage(conversation_id: GetMessagePathParams["conversation_id"], message_id: GetMessagePathParams["message_id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetMessageQueryResponse, ResponseErrorConfig<GetMessage422>, unknown>({ method : "GET", url : getGetMessageUrl(conversation_id, message_id).url.toString(), ... requestConfig })  
  return res.data
}