/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../lib/axios-instance";
import type { RequestConfig, ResponseErrorConfig } from "../../lib/axios-instance";
import type { HealthCheckHealthGetQueryResponse } from "../types/HealthCheckHealthGet.ts";

function getHealthCheckHealthGetUrl() {
  const res = { method: 'GET', url: `/health` as const }  
  return res
}

/**
 * @summary Health Check
 * {@link /health}
 */
export async function healthCheckHealthGet(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<HealthCheckHealthGetQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getHealthCheckHealthGetUrl().url.toString(), ... requestConfig })  
  return res.data
}