/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../lib/axios-instance";
import type { RequestConfig, ResponseErrorConfig } from "../../lib/axios-instance";
import type { ListConversationsQueryResponse, ListConversationsQueryParams, ListConversations422 } from "../types/ListConversations.ts";

function getListConversationsUrl() {
  const res = { method: 'GET', url: `/conversations/` as const }  
  return res
}

/**
 * @summary List Conversations
 * {@link /conversations/}
 */
export async function listConversations(params?: ListConversationsQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<ListConversationsQueryResponse, ResponseErrorConfig<ListConversations422>, unknown>({ method : "GET", url : getListConversationsUrl().url.toString(), params, ... requestConfig })  
  return res.data
}