/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../lib/axios-instance";
import type { RequestConfig, ResponseErrorConfig } from "../../lib/axios-instance";
import type { ListMessagesQueryResponse, ListMessagesPathParams, ListMessagesQueryParams, ListMessages422 } from "../types/ListMessages.ts";

function getListMessagesUrl(conversation_id: ListMessagesPathParams["conversation_id"]) {
  const res = { method: 'GET', url: `/conversations/${conversation_id}/messages/` as const }  
  return res
}

/**
 * @summary List Messages
 * {@link /conversations/:conversation_id/messages/}
 */
export async function listMessages(conversation_id: ListMessagesPathParams["conversation_id"], params?: ListMessagesQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<ListMessagesQueryResponse, ResponseErrorConfig<ListMessages422>, unknown>({ method : "GET", url : getListMessagesUrl(conversation_id).url.toString(), params, ... requestConfig })  
  return res.data
}