/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../lib/axios-instance";
import type { RequestConfig, ResponseErrorConfig } from "../../lib/axios-instance";
import type { RootGetQueryResponse } from "../types/RootGet.ts";

function getRootGetUrl() {
  const res = { method: 'GET', url: `/` as const }  
  return res
}

/**
 * @summary Root
 * {@link /}
 */
export async function rootGet(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<RootGetQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getRootGetUrl().url.toString(), ... requestConfig })  
  return res.data
}