/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../lib/axios-instance";
import type { RequestConfig, ResponseErrorConfig } from "../../lib/axios-instance";
import type { UpdateConversationMutationRequest, UpdateConversationMutationResponse, UpdateConversationPathParams, UpdateConversation422 } from "../types/UpdateConversation.ts";

function getUpdateConversationUrl(conversation_id: UpdateConversationPathParams["conversation_id"]) {
  const res = { method: 'PUT', url: `/conversations/${conversation_id}` as const }  
  return res
}

/**
 * @summary Update Conversation
 * {@link /conversations/:conversation_id}
 */
export async function updateConversation(conversation_id: UpdateConversationPathParams["conversation_id"], data?: UpdateConversationMutationRequest, config: Partial<RequestConfig<UpdateConversationMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<UpdateConversationMutationResponse, ResponseErrorConfig<UpdateConversation422>, UpdateConversationMutationRequest>({ method : "PUT", url : getUpdateConversationUrl(conversation_id).url.toString(), data : requestData, ... requestConfig })  
  return res.data
}