/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../lib/axios-instance";
import type { RequestConfig, ResponseErrorConfig } from "../../lib/axios-instance";
import type { HealthCheckHealthGetQueryResponse } from "../types/HealthCheckHealthGet.ts";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { healthCheckHealthGet } from "../client/healthCheckHealthGet.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const healthCheckHealthGetSuspenseQueryKey = () => [{ url: '/health' }] as const

export type HealthCheckHealthGetSuspenseQueryKey = ReturnType<typeof healthCheckHealthGetSuspenseQueryKey>

export function healthCheckHealthGetSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = healthCheckHealthGetSuspenseQueryKey()
  return queryOptions<HealthCheckHealthGetQueryResponse, ResponseErrorConfig<Error>, HealthCheckHealthGetQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return healthCheckHealthGet(config)
   },
  })
}

/**
 * @summary Health Check
 * {@link /health}
 */
export function useHealthCheckHealthGetSuspense<TData = HealthCheckHealthGetQueryResponse, TQueryKey extends QueryKey = HealthCheckHealthGetSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<HealthCheckHealthGetQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? healthCheckHealthGetSuspenseQueryKey()

  const query = useSuspenseQuery({
   ...healthCheckHealthGetSuspenseQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}