/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../lib/axios-instance";
import type { RequestConfig, ResponseErrorConfig } from "../../lib/axios-instance";
import type { ListConversationsQueryResponse, ListConversationsQueryParams, ListConversations422 } from "../types/ListConversations.ts";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { listConversations } from "../client/listConversations.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const listConversationsQueryKey = (params?: ListConversationsQueryParams) => [{ url: '/conversations/' }, ...(params ? [params] : [])] as const

export type ListConversationsQueryKey = ReturnType<typeof listConversationsQueryKey>

export function listConversationsQueryOptions(params?: ListConversationsQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = listConversationsQueryKey(params)
  return queryOptions<ListConversationsQueryResponse, ResponseErrorConfig<ListConversations422>, ListConversationsQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return listConversations(params, config)
   },
  })
}

/**
 * @summary List Conversations
 * {@link /conversations/}
 */
export function useListConversations<TData = ListConversationsQueryResponse, TQueryData = ListConversationsQueryResponse, TQueryKey extends QueryKey = ListConversationsQueryKey>(params?: ListConversationsQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<ListConversationsQueryResponse, ResponseErrorConfig<ListConversations422>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? listConversationsQueryKey(params)

  const query = useQuery({
   ...listConversationsQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<ListConversations422>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}