/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../../lib/axios-instance";
import type { RequestConfig, ResponseErrorConfig } from "../../lib/axios-instance";
import type { RootGetQueryResponse } from "../types/RootGet.ts";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { rootGet } from "../client/rootGet.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const rootGetQueryKey = () => [{ url: '/' }] as const

export type RootGetQueryKey = ReturnType<typeof rootGetQueryKey>

export function rootGetQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = rootGetQueryKey()
  return queryOptions<RootGetQueryResponse, ResponseErrorConfig<Error>, RootGetQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return rootGet(config)
   },
  })
}

/**
 * @summary Root
 * {@link /}
 */
export function useRootGet<TData = RootGetQueryResponse, TQueryData = RootGetQueryResponse, TQueryKey extends QueryKey = RootGetQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<RootGetQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? rootGetQueryKey()

  const query = useQuery({
   ...rootGetQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}