"""Add system_prompt to conversations

Revision ID: 81c1476612b3
Revises: c5d264def611
Create Date: 2025-09-22 10:08:50.914245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81c1476612b3'
down_revision: Union[str, Sequence[str], None] = 'c5d264def611'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('system_prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'system_prompt')
    # ### end Alembic commands ###
