"""Support thinking

Revision ID: 88409616ef43
Revises: 0b6721251d70
Create Date: 2025-09-22 19:29:48.057054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88409616ef43'
down_revision: Union[str, Sequence[str], None] = '0b6721251d70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE messagerole ADD VALUE 'THINKING'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE messagerole DROP VALUE 'THINKING'")
    # ### end Alembic commands ###
