apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: python-ai
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: python-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/pukar10/python-ai-backend:latest
          ports:
            - containerPort: 8000
          env:
            - { name: DB_HOST,         value: "postgres" }
            - { name: DB_PORT,         value: "5432" }
            - { name: DB_NAME,         value: "chat_db" }
            - { name: DB_USER,         value: "postgres" }
            - { name: DB_PASSWORD,     value: "postgres" }
            - { name: OLLAMA_BASE_URL, value: "http://ollama:11434" }
            - { name: OLLAMA_MODEL,    value: "llama3.2" }
          readinessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
