/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ChatRequest } from "./ChatRequest.ts";
import type { HTTPValidationError } from "./HTTPValidationError.ts";

/**
 * @description Successful Response
*/
export type ChatStream200 = any;

/**
 * @description Validation Error
*/
export type ChatStream422 = HTTPValidationError;

export type ChatStreamMutationRequest = ChatRequest;

export type ChatStreamMutationResponse = ChatStream200;

export type ChatStreamMutation = {
    Response: ChatStream200;
    Request: ChatStreamMutationRequest;
    Errors: ChatStream422;
};