/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type Conversation = {
    /**
     * @default "New Conversation"
    */
    title?: (string | null);
    /**
     * @type integer
    */
    id: number;
    /**
     * @type string, date-time
    */
    created_at: string;
    /**
     * @type string, date-time
    */
    updated_at: string;
};