/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HTTPValidationError } from "./HTTPValidationError.ts";
import type { Message } from "./Message.ts";
import type { MessageCreate } from "./MessageCreate.ts";

export type CreateMessagePathParams = {
    /**
     * @type integer
    */
    conversation_id: number;
};

/**
 * @description Successful Response
*/
export type CreateMessage200 = Message;

/**
 * @description Validation Error
*/
export type CreateMessage422 = HTTPValidationError;

export type CreateMessageMutationRequest = MessageCreate;

export type CreateMessageMutationResponse = CreateMessage200;

export type CreateMessageMutation = {
    Response: CreateMessage200;
    Request: CreateMessageMutationRequest;
    PathParams: CreateMessagePathParams;
    Errors: CreateMessage422;
};