/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Conversation } from "./Conversation.ts";
import type { ConversationCreate } from "./ConversationCreate.ts";
import type { HTTPValidationError } from "./HTTPValidationError.ts";

/**
 * @description Successful Response
*/
export type CreateConversation200 = Conversation;

/**
 * @description Validation Error
*/
export type CreateConversation422 = HTTPValidationError;

export type CreateConversationMutationRequest = ConversationCreate;

export type CreateConversationMutationResponse = CreateConversation200;

export type CreateConversationMutation = {
    Response: CreateConversation200;
    Request: CreateConversationMutationRequest;
    Errors: CreateConversation422;
};