/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HTTPValidationError } from "./HTTPValidationError.ts";

export type DeleteMessagePathParams = {
    /**
     * @type integer
    */
    conversation_id: number;
    /**
     * @type integer
    */
    message_id: number;
};

/**
 * @description Successful Response
*/
export type DeleteMessage200 = any;

/**
 * @description Validation Error
*/
export type DeleteMessage422 = HTTPValidationError;

export type DeleteMessageMutationResponse = DeleteMessage200;

export type DeleteMessageMutation = {
    Response: DeleteMessage200;
    PathParams: DeleteMessagePathParams;
    Errors: DeleteMessage422;
};