/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HTTPValidationError } from "./HTTPValidationError.ts";

export type DeleteConversationPathParams = {
    /**
     * @type integer
    */
    conversation_id: number;
};

/**
 * @description Successful Response
*/
export type DeleteConversation200 = any;

/**
 * @description Validation Error
*/
export type DeleteConversation422 = HTTPValidationError;

export type DeleteConversationMutationResponse = DeleteConversation200;

export type DeleteConversationMutation = {
    Response: DeleteConversation200;
    PathParams: DeleteConversationPathParams;
    Errors: DeleteConversation422;
};