/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ConversationWithMessages } from "./ConversationWithMessages.ts";
import type { HTTPValidationError } from "./HTTPValidationError.ts";

export type GetConversationPathParams = {
    /**
     * @type integer
    */
    conversation_id: number;
};

/**
 * @description Successful Response
*/
export type GetConversation200 = ConversationWithMessages;

/**
 * @description Validation Error
*/
export type GetConversation422 = HTTPValidationError;

export type GetConversationQueryResponse = GetConversation200;

export type GetConversationQuery = {
    Response: GetConversation200;
    PathParams: GetConversationPathParams;
    Errors: GetConversation422;
};