/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HTTPValidationError } from "./HTTPValidationError.ts";
import type { Message } from "./Message.ts";

export type GetMessagePathParams = {
    /**
     * @type integer
    */
    conversation_id: number;
    /**
     * @type integer
    */
    message_id: number;
};

/**
 * @description Successful Response
*/
export type GetMessage200 = Message;

/**
 * @description Validation Error
*/
export type GetMessage422 = HTTPValidationError;

export type GetMessageQueryResponse = GetMessage200;

export type GetMessageQuery = {
    Response: GetMessage200;
    PathParams: GetMessagePathParams;
    Errors: GetMessage422;
};