/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Conversation } from "./Conversation.ts";
import type { HTTPValidationError } from "./HTTPValidationError.ts";

export type ListConversationsQueryParams = {
    /**
     * @default 0
     * @type integer | undefined
    */
    skip?: number;
    /**
     * @default 20
     * @type integer | undefined
    */
    limit?: number;
};

/**
 * @description Successful Response
*/
export type ListConversations200 = Conversation[];

/**
 * @description Validation Error
*/
export type ListConversations422 = HTTPValidationError;

export type ListConversationsQueryResponse = ListConversations200;

export type ListConversationsQuery = {
    Response: ListConversations200;
    QueryParams: ListConversationsQueryParams;
    Errors: ListConversations422;
};