/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HTTPValidationError } from "./HTTPValidationError.ts";
import type { Message } from "./Message.ts";

export type ListMessagesPathParams = {
    /**
     * @type integer
    */
    conversation_id: number;
};

export type ListMessagesQueryParams = {
    /**
     * @default 0
     * @type integer | undefined
    */
    skip?: number;
    /**
     * @default 100
     * @type integer | undefined
    */
    limit?: number;
};

/**
 * @description Successful Response
*/
export type ListMessages200 = Message[];

/**
 * @description Validation Error
*/
export type ListMessages422 = HTTPValidationError;

export type ListMessagesQueryResponse = ListMessages200;

export type ListMessagesQuery = {
    Response: ListMessages200;
    PathParams: ListMessagesPathParams;
    QueryParams: ListMessagesQueryParams;
    Errors: ListMessages422;
};