/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { MessageRole } from "./MessageRole.ts";

export type MessageCreate = {
    /**
     * @type string
    */
    role: MessageRole;
    /**
     * @type string
    */
    content: string;
};