/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { MessageRole } from "./MessageRole.ts";

export type Message = {
    /**
     * @type string
    */
    role: MessageRole;
    /**
     * @type string
    */
    content: string;
    /**
     * @type integer
    */
    id: number;
    /**
     * @type integer
    */
    conversation_id: number;
    /**
     * @type string, date-time
    */
    created_at: string;
};