/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Conversation } from "./Conversation.ts";
import type { ConversationUpdate } from "./ConversationUpdate.ts";
import type { HTTPValidationError } from "./HTTPValidationError.ts";

export type UpdateConversationPathParams = {
    /**
     * @type integer
    */
    conversation_id: number;
};

/**
 * @description Successful Response
*/
export type UpdateConversation200 = Conversation;

/**
 * @description Validation Error
*/
export type UpdateConversation422 = HTTPValidationError;

export type UpdateConversationMutationRequest = ConversationUpdate;

export type UpdateConversationMutationResponse = UpdateConversation200;

export type UpdateConversationMutation = {
    Response: UpdateConversation200;
    Request: UpdateConversationMutationRequest;
    PathParams: UpdateConversationPathParams;
    Errors: UpdateConversation422;
};