---
- name: Download Helm install script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: /tmp/get-helm-3.sh
    mode: "0755"

- name: Run Helm install script
  ansible.builtin.command: /tmp/get-helm-3.sh
  args:
    creates: /usr/local/bin/helm

- name: Verify Helm installation
  ansible.builtin.command: helm version --short
  register: helm_version
  changed_when: false

- name: Show Helm version
  ansible.builtin.debug:
    msg: "Helm installed: {{ helm_version.stdout }}"