- name: Install hybrid k3s on PRIMARY node
  hosts: "k8s_nodes[0]"
  gather_facts: false
  become: true
  roles:
    - k8s_install_k3s

- name: Verify k3s install
  hosts: k3_nodes
  gather_facts: false
  become: true
  roles:
    - k8-verify_k3s_install